---
# tasks file for ansible-role-install-nodejs
- name: Install prerequisite packages, and update apt cache
  apt:
    name: "{{ nodejs_prereqs }}"
    update_cache: yes
  become: yes

- name: Add nodesource GPG key with apt-key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
  become: yes
